image: node:16-alpine

cache:
  paths:
    - node_modules

before_script:
  - npm install

lint:
  stage: test
  script:
    - npm run lint

pages:
  stage: deploy
  script:
    - npm run build
    - npm run export
    - mv out public
  artifacts:
    paths:
      - public
